import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import TopBar from "@/components/layout/TopBar";
import MobileNav from "@/components/layout/MobileNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" hidden md:block">
        <div className="fixed top-0 left-0 right-0 bottom-0 bg-black my-10  mx-[8%] opacity-75 z-[-10] rounded-2xl   shadow-xl shadow-blue-500"></div>
        </div>
        
        <div className="md:my-10 md:mx-[8%] md:p-4  md:flex z-10">
          <Sidebar />
          <div className=" w-full">
            <TopBar />
            <MobileNav/>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
